### ISSUE TITLE
Switch to Android Studio

### ISSUE THREAD

**Issue by burrito82** [Toweli/Loreli#15]
The current way of writing android apps is using [Android Studio](https://developer.android.com/sdk/index.html), not Eclipse anymore. How about switching to it now? It should be done eventually, and currently it would be easier since we don't have much stuff anyway.

**Edit:** [Here](http://stackoverflow.com/a/26196451) is described how to run plain java projects in Android Studio, but I didn't test it yet.

**Comment by Toweli** [comment]
Sounds to simple. I'll test it the next days

**Comment by Toweli** [comment]
no more question
it's a todo now

**Comment by Toweli** [comment]
Finished
